name: Build and Publish Python package

on:
    push:
        branches:
            - 'DEVOPS-425'
env:
    PACKAGE_NAME: 'my-repo'
    VERSION: '0.1.0'
    BRANCH_NAME: ''
    BUILD_NUMBER: '12'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout code
            uses: actions/checkout@v3
        -   name: Install grayskull
            run: |
                python -m pip install grayskull
        -   name: Archive my repository
            run: |
                git archive --format=tar.gz HEAD > "$PACKAGE_NAME-$VERSION-$BRANCH_NAME-$BUILD_NUMBER.tar.gz"
        -   name: Create conda recipe
            run: |
                grayskull pypi --strict-conda-forge "$PACKAGE_NAME-$VERSION-$BRANCH_NAME-$BUILD_NUMBER.tar.gz"
        -   name: Build conda package
            run: |
                output=$(conda build $PACKAGE_NAME --output)
        -   name: Publish conda package
            run: |
                curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -T $output "https://mirageoscienceltd.jfrog.io/artifactory/dev/$PACKAGE_NAME/$VERSION/$PACKAGE_NAME-$VERSION-$BUILD_NUMBER.tar.bz2"

         
