name: static analysis

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
      - DEVOPS-427 # Temporary branch for testing

jobs:
  call-workflow-jira-issue:
    uses: MiraGeoscience/DevTool/.github/workflows/static-analysis.yml@DEVOPS-427
